### ISSUE TITLE
运行demo 报错Cannot set property readyState of #<t>

### ISSUE THREAD

**Issue by iCloudys** [easemob/webim-uniapp-demo#11]
直接拉下来代码，用HbuiderX运行后，输入账户密码登录报如下错误
{apiUrl: "https://a1.easemob.com", user: "1", pwd: "123456", grant_type: "password", appKey: "easemob-demo#chatdemoui"}
apiUrl: "https://a1.easemob.com"
appKey: "easemob-demo#chatdemoui"
grant_type: "password"
pwd: "123456"
user: "1"
}
----------------------------------------------------------------
[system] thirdScriptError
TypeError: Cannot set property readyState of #<t> which has only a getter;at socketTask.onOpen callback function
 TypeError: Cannot set property readyState of #<t> which has only a getter
    at eval (wxsdk3.4.0.js:1)
    at chunk-vendors.js:306
    at Array.forEach (<anonymous>)
    at WebSocket.<anonymous> (chunk-vendors.js:306)

界面上一直提示 正在初始化客户端..

**Comment by masterchen** [comment]
遇到了同样的错误，换成自己的appkey,  也是无法登陆，程序返回：
{
	"type": 1,
	"message": "login failed",
	"data": {
		"errMsg": "request:fail abort statusCode:-1 Unable to resolve host \"a1.easemob.com\": No address associated with hostname"
	}
}

**Comment by iCloudys** [comment]
已经解决了，在WebIM.js的文件中，第一行引入的js_sdk,需要更换同目录下的另外一个，就能登录了。
楼上换成自己的appkey无法登录我也遇到了，修改WebIMConfig.js里面的xmppURL和apiURL,总有一个能登录的，用官网上提示的不对
