### ISSUE TITLE
咨询一下聊天对话发送文件

### ISSUE THREAD

**Issue by purposeZhangxiang** [easemob/webim-uniapp-demo#31]
在uniapp是否能实现聊天对话发送文件，最终目标是生成ios以及安卓应用。无相应的demo进行参考

**Comment by Wster11** [comment]
可以更新一下master分支的代码，新增了附件消息的实现， 文件预览需要在真机上测试。

**Comment by purposeZhangxiang** [comment]
> 
大佬响应的真快~感谢~ 恰好昨天晚上自己也发现了uni.chooseFile api的位置写明了，在uni插件市场里有很多非媒体文件上传的插件。android可通过nativejs去拉起实现，ios只能是原生插件。
