### ISSUE TITLE
【关于h5端上传环信消息服务器的疑问】

### ISSUE THREAD

**Issue by purposeZhangxiang** [easemob/webim-uniapp-demo#35]
uni在h5的选择媒体资源或者非媒体资源文件在选择成功回调里的filepath 是一个blob url (blob:http://localhostxxx-xxxx-xxx)  用blob url上传到环信消息服务器会报错提示不支持该类型文件。而在app环境下选择出的文件是file:///xxxxx/xxx/sss.json这种形式的文件路径 上传就不会有问题。试问h5端应该怎么处理上传这块

**Comment by Wster11** [comment]
blobUrl可以正常使用浏览器下载的话，demo中有在h5上传blob语音消息的示例 [audio](https://github.com/easemob/webim-uniapp-demo/blob/master/components/chat/inputbar/suit/audio/audio.vue)
