### ISSUE TITLE
z这个支持vue2吗？

### ISSUE THREAD

**Issue by Jack-QMY** [easemob/webim-uniapp-demo#56]
我看在DCLOUD市场上说在vue2平台上的兼容性不行，只在vue3上
![image](https://github.com/easemob/webim-uniapp-demo/assets/57746139/7274367b-6075-4345-9175-70ee2b5db248)

**Comment by Wster11** [comment]
支持vue2，master分支为vue2版本的Demo, vue3分之为vue3版本的Demo。
